### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jclaessens97** [jclaessens97/PlaylistManager#1]
# TODO

## Repository
- [ ] Add dependencies to readme

### Audio player
- [x] Play/Pause/Skip audio files
- [x] Navigate through song with seekbar
- [x] Change volume of song with slider
- [x] Shuffle
- [x] Repeat
- [x] Song goes to next if end is reached
- [x] Add possibility to pause between songs (adjustable in settings)
- [ ] Holding next or prev should fastforward
- [ ] Prev should first go to begin of the song

### Library
- [x] Load folder with audio files
- [x] Sort playlists by clicking on title row
- [ ] Edit ID3 tags of audiofiles when in editmode
- [ ] Searchfunction
- [ ] Possibility to clear selection
- [x] Duration formatting in datagrid
- [ ] Select which columns to show by rightclicking header row with contextmenu

### Playlists
- [ ] Create new playlist
- [ ] Modify playlist
- [ ] Save playlists
- [ ] Export playlists (research: possible playlistformats)

### Settings
- [ ] Change folder where library needs to get its songs
- [ ] change theme
- [ ] enable keyboard media shortcuts when minimized

### GUI
- [ ] Fully implement materialdesign for WPF
- [x] Create media player 
- [x] Set buttons to correct state (lower volume = mute button lower volume, shuffle toggle, ...)
- [ ] Add indicator into listview which song is playing
- [ ] Add a quick menu to see the current playing list (if selection or playlist, else only next and prev one)
- [x] If value is null or 0 in gridview, hide it
- [ ] Mediabuttons in taskbar: https://msdn.microsoft.com/en-us/library/windows/desktop/dd378460(v=vs.85).aspx
- [ ] Light & Dark version (I Think I make the dark one first :p materialDesign lib makes it easy to change tho )

## Performance
- [ ] Implement async loading (e.g. library)

## Advanced functionality
- [ ] Connect to (android) device to copy created playlist
- [ ] Profile system (manage playlist per user)
- [ ] Smart playlists

**Comment by jclaessens97** [comment]
Moved TODO to [Trello](https://trello.com/b/KuC2hh4v)
