### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jclaessens97** [jclaessens97/PlaylistManager#1]
TODO list of the project:

### Audio player
- [ ] Play/Pause/Skip audio files
### Library
- [ ] Create new playlist
- [ ] Save playlists
- [ ] Load folder with audio files
- [ ] Edit ID3 tags of audiofiles
- [ ] Export playlists (research: possible playlistformats)
### GUI
WINFORMS or WPF **???**
- [ ] Create media player 

Create listview of: 
- [ ] Library
- [ ] Playlists
 
## Advanced functionality
- [ ] Connect to (android) device to copy created playlist
